
output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}
#---------------------------------------------------
output "key_alias_arn" {
  description = "The arn of the key alias"
  value       = aws_kms_alias.key_alias.arn
}

output "key_alias_name" {
  description = "The name of the key alias"
  value       = aws_kms_alias.key_alias.name
}

output "key_arn" {
  description = "The arn of the key"
  value       = aws_kms_key.key.arn
}

output "key_id" {
  description = "The globally unique identifier for the key"
  value       = aws_kms_key.key.id
}
