apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: webpage-application
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: webpage-application
  template:
    metadata:
      labels:
        app: webpage-application
    spec:
      containers:
      - name: webpage-application-container
        image: 001033/scsi:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 15m
        readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 10
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-application-service
spec:
  #Creating a service of type load balancer. Load balancer gets created but takes time to reflect
  type: LoadBalancer 
  selector:
    app: webpage-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

