apiVersion: ENC[AES256_GCM,data:Os7co+GyBQ==,iv:2U0rgdawNJJKmnji2qeoRo7HNBIH7A28sEKjBpCoV4Q=,tag:RG6ANxpZdvIGA+lMCeE/hg==,type:str]
kind: ENC[AES256_GCM,data:uKGTCH9d+Wh68w==,iv:ffKDtJshkC5S0sP8ujmU1V7hE7GUj7DasJ4+KgFRFvI=,tag:/4eaOXjkUyIcWEzPPGk/Mw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2ZrgpDdWh8ImuFQC6j3AiJPllGWJqzE=,iv:BOGlUVIxbSJlJV+Yoitz6/gcCQOoBBS/uPFh4Zj8yRI=,tag:mFD5eJSzM2/iCKZDzjHbgw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:n4UF/McE6+qmmjKEPypfhDxnIw==,iv:zsiNITU3qj8FAZAnlxUMssEv6CfPyQnW1ULhCN4eHg0=,tag:HrTiGJzIp+DDudnM/9WuRA==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:JQ==,iv:om6M3LLSLKbMLeLnb67oSL5JikovyMdJjwjq7+FMOco=,tag:yxM3AJw23mSYyqEKIw2rqw==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:RWM5sV0tsuZuxElIwHY0RlA7Eg==,iv:N5vcpJ9MvM/Yd35R6unJSAlXVF19QZpyCwKVwOBZcec=,tag:e+W+cAHee83onvxJ/1DqSA==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:6qKUnESCjxJK3DM0wlXjfPvyRA==,iv:7U7dLlnIbE6BLiLu+R6U1glTqyNbMC1GyvOKlu8ZKfw=,tag:vvq7bGUC0AwbmAcrZP1jNw==,type:str]
        spec:
            containers:
            -   name: ENC[AES256_GCM,data:6r1se+ckFzvgxMW3culQ72d17zkyOuLB2aIPrLI=,iv:b8mvUEWOvqpgHWt2i5K+bRbTmxyw/wlYVNEBcV5Y2Fs=,tag:WbeYqGkr2HVC7c1pSe1/TA==,type:str]
                image: ENC[AES256_GCM,data:R6S/RZKYAJoJLkSg1YVgE5Rx,iv:0+pzHT7xCCHHiLI+SQn/CFcMPmkHGa5Qwi1ety4m5k4=,tag:exmmvlOKQq+tZv2BXuvq3A==,type:str]
                ports:
                -   containerPort: ENC[AES256_GCM,data:cHk=,iv:lM6J9fhmmStgN91Accvk7dr1ouAvzXoOG9vWP+qwLU4=,tag:w+7ouzJ6h+R2mEN1pCJhvQ==,type:int]
                resources:
                    requests:
                        memory: ENC[AES256_GCM,data:DlC8Gg==,iv:rVjDWj//q5f5MH1WIBV00c4UVRxUfu4T1lT2l4PjV40=,tag:HZ3Q/60qor+efobFmsi8kQ==,type:str]
                        cpu: ENC[AES256_GCM,data:9XiU,iv:SQrFvKpQPABreM2Yo13k1GA1FUf+LvZZvw2O1fdftvY=,tag:+tuErQ7XtoMxfh0WshCcLw==,type:str]
                    limits:
                        memory: ENC[AES256_GCM,data:U1N0kL8=,iv:5WUwr3+lSWtMcBL/RUn9JWYUGnCiEeTjhcQMVZrFKK4=,tag:MU3+yn8TAk9uWKS8UYsQRA==,type:str]
                        cpu: ENC[AES256_GCM,data:2sf9,iv:Z7GSX1Ia3VqWUBTFdTqZJXjkpYomiWA4ZLEfSF9PGek=,tag:kLSuR3dphEL7CDXUF8/JCw==,type:str]
                readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:/A==,iv:wj+PH4P7Lhsuf6kE+QSII8FaboSE6J4euCE/PMZwQCI=,tag:/LUmPXzETBKvDxCGnstNhg==,type:str]
                        port: ENC[AES256_GCM,data:Pbk=,iv:OF+bbfnpIBNTdf3oyzLmx4bmla8t2cOHJttAggQ0OUg=,tag:Y+16vdWmX58dSIrRKHp0Eg==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:HY4=,iv:wIXPlieQnRUrAR0wbPzRQLj3BPkWQI8mza5ztSGj9LY=,tag:cEABlnDtW979bCCfP+RIfA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:hQ==,iv:zp8NoPgPCo/PX1PfRITikmsZAvtafzPJ0x81FxYMeAs=,tag:sySPF1ImsMfiNEzippJRog==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:Aw==,iv:ZItL3cS3TL8+izAWixLqSGQc81kgVxjbe/JKWBQNgnU=,tag:eO3TfVX2atWWxh6dpv1Apg==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:moA=,iv:6ZVRjg8GpGTxAJAhpIi6cwgkLlYOTM5XEcItzXIPQ10=,tag:potS8XKxONl/xq8RIhPzlw==,type:int]
                livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:yQ==,iv:4aFNdWRkHimn69AAA0KD3LwnlANhKcX8DlJYuXVTwwg=,tag:ddr66uRuXld9jpybYCyS/w==,type:str]
                        port: ENC[AES256_GCM,data:Bh4=,iv:U5ZNTYe734BsL/zuobjUBJTJ6YOyEADg0BtnP9EZ6GI=,tag:vlNXWYCsE3JLk5NOWlf6VQ==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:Rms=,iv:ZYGk0U1/tLkSh1x2o2YvS/kCs7y9TJy/MEIl3BPVoRE=,tag:0XFiOSnwieQbHNeo45HYQg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:FA==,iv:oy8Nmyy2tINNPONhcZNkBxHNCoqslDYd2Z2YDoI0aDA=,tag:NWHpooMD4JZwCZOjPMejlw==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:+Q==,iv:048JhRsAp7Dp9Xl/eVnrSo8Z6HwVG9Ub9ekXZK9t114=,tag:UKl3u6ZMPkWpBDSQl/7hww==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:l1Y=,iv:3k2ulnX9v/8gD7le1FiwqFepJQHjqFYgfBJGajLmmmQ=,tag:lDNnrpvY821wm554QqzyaA==,type:int]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    kms:
    -   arn: arn:aws:kms:eu-central-1:513910674915:key/8d653fa0-d35c-4ab6-8e6f-552a5f756025
        enc: AQICAHiRJ3Wve9uQicS/MprFo/u1o8NHeYFyImvWYb62HwpxvAEI0Bf9BoJs8K5Y7+CQMdAcAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYcqZ+83revtNv81mAgEQgDscAnpNmP6Nkfxkcaab9lOf8/3Q6lvtvnpEyIpwwNd7JJtlHImByDlKGpC3rPRmM6Fmj1G0maIfkpkZ1Q==
        created_at: '2021-10-02T20:44:31Z'
    lastmodified: '2021-10-02T20:44:31Z'
    mac: ENC[AES256_GCM,data:ATtYrgst9Z5+GiX27N4tUmBdCAUo0QF/C414iYv0Fk6K1zspVVanu/9JQMQkdmsz+JzoX+Rd/WuRRBucWAtL5C5uBD0U0CGjRyshr21vd3UvNl86SSzue8brMTWZsccTuzLxshGcfjiojWnAVqxIqiyK9Df0s0Dssdrwo69F9AY=,iv:zuh9+ldmRlWpr7ja3Ms0uHhQgOPLgtk7Xj9XBFXNXqY=,tag:zLkw3E/+/TALbCUYrqx3kg==,type:str]
