apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adil
  namespace: default # Should be namespace you are granting access to
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: adil # Should match name of Role
subjects:
- namespace: adil # Should match namespace where SA lives
  kind: ServiceAccount
  name: adil # Should match service account name, above
