apiVersion: v1
kind: Service
metadata:
  name: webpage-application-service
spec:
  #Creating a service of type load balancer. Load balancer gets created but takes time to reflect
  type: LoadBalancer 
  selector:
    app: webpage-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
